services:
  root-page:
    image: nginx:alpine
    container_name: root-page
    restart: unless-stopped

    volumes:
      - ./html:/usr/share/nginx/html:ro

    networks:
      - traefik-network

    labels:
      - "traefik.enable=true"

      # HTTPS
      - "traefik.http.routers.root-page.rule=Host(`kykyrudza.com`) || Host(`www.kykyrudza.com`)"
      - "traefik.http.routers.root-page.entrypoints=websecure"
      - "traefik.http.routers.root-page.tls=true"
      - "traefik.http.routers.root-page.tls.certresolver=myresolver"

      # Nginx
      - "traefik.http.services.root-page.loadbalancer.server.port=80"

      # HTTP -> HTTPS
      - "traefik.http.routers.root-page-http.rule=Host(`kykyrudza.com`) || Host(`www.kykyrudza.com`)"
      - "traefik.http.routers.root-page-http.entrypoints=web"
      - "traefik.http.routers.root-page-http.middlewares=root-page-redirect"
      - "traefik.http.middlewares.root-page-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.root-page-redirect.redirectscheme.permanent=true"

networks:
  traefik-network:
    external: true